# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\FMOD_Script\FMOD_Script\git_fmod\ui/dirty_list_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirtyListWidgetWindow(object):
    def setupUi(self, DirtyListWidgetWindow):
        DirtyListWidgetWindow.setObjectName("DirtyListWidgetWindow")
        DirtyListWidgetWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DirtyListWidgetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_ListView = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_ListView.setObjectName("tableWidget_ListView")
        self.tableWidget_ListView.setColumnCount(0)
        self.tableWidget_ListView.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_ListView)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ShowDiff = QtWidgets.QToolButton(self.frame_2)
        self.btn_ShowDiff.setObjectName("btn_ShowDiff")
        self.verticalLayout.addWidget(self.btn_ShowDiff)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        DirtyListWidgetWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DirtyListWidgetWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        DirtyListWidgetWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DirtyListWidgetWindow)
        self.statusbar.setObjectName("statusbar")
        DirtyListWidgetWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DirtyListWidgetWindow)
        QtCore.QMetaObject.connectSlotsByName(DirtyListWidgetWindow)

    def retranslateUi(self, DirtyListWidgetWindow):
        _translate = QtCore.QCoreApplication.translate
        DirtyListWidgetWindow.setWindowTitle(_translate("DirtyListWidgetWindow", "Dirty List"))
        self.btn_ShowDiff.setText(_translate("DirtyListWidgetWindow", "Show Diff"))
